In [1]:
import os
import pandas as pd
import numpy as np
from Tkinter import *
import tkSnack
root = Tk()
tkSnack.initializeSnack(root)

import matplotlib.pyplot as plt
%matplotlib notebook

C:\Python27\lib\site-packages\IPython\kernel\__init__.py:13: ShimWarning: The `IPython.kernel` package has been deprecated. You should import from ipykernel or jupyter_client instead.
  "You should import from ipykernel or jupyter_client instead.", ShimWarning)


In [2]:
path = "c:/Python27/qp2_py/frechet_distance/speakers/"
allFiles = os.listdir(path)
for name in allFiles:
    fname = path+name
    distances = pd.read_csv(fname, sep="_", header=None)
#print distances

In [3]:
distances.columns= ["speakerID", "speakerIPU", "comp_speaker", "comp_speakerIPU","frechetdistance"]

In [4]:
distances

speakerID  speakerIPU  comp_speaker  comp_speakerIPU  frechetdistance
0               0           0             1                0        65.249969
1               0           0             1                1        66.515404
2               0           0             1                2       274.112701
3               0           0             1                3        84.120514
4               0           0             1                4       157.210114
5               0           0             1                5        79.410965
6               0           0             1                6        66.920204
7               0           0             1                7       129.865005
8               0           0             1                8        87.305168
9               0           0             1                9        70.002014
10              0           0             1               10       121.547394
11              0           0             1               11       133.760040
12              0           0             1               12        70.600319
13              0           0             1               13       116.680733
14              0           0             1               14        88.052719
15              0           0             1               15        31.481182
16              0           0             1               16        87.957268
17              0           0             1               17        89.296844
18              0           0             1               18        56.891933
19              0           0             1               19       353.062225
20              0           0             1               20       109.890099
21              0           0             1               21        68.659462
22              0           0             1               22        83.948578
23              0           0             1               23        88.865791
24              0           0             1               24        37.910965
25              0           0             1               25        77.620163
26              0           0             1               26        67.401115
27              0           0             1               27        25.594454
28              0           0             1               28       120.141197
29              0           0             1               29        75.341499
...           ...         ...           ...              ...              ...
229092         11           1            39               37       114.561859
229093         11           1            39               38        69.395935
229094         11           1            39               39        73.270012
229095         11           1            39               40        69.394905
229096         11           1            39               41       122.228127
229097         11           1            39               42       118.530014
229098         11           1            39               43        33.050549
229099         11           1            39               44       122.551674
229100         11           1            39               45        69.396530
229101         11           1            39               46        63.455727
229102         11           1            39               47       149.760010
229103         11           1            39               48       134.450195
229104         11           1            39               49       133.429993
229105         11           1            39               50       111.330017
229106         11           1            39               51       159.154892
229107         11           1            39               52       151.880005
229108         11           1            39               53        59.040154
229109         11           1            39               54        59.039284
229110         11           1            39               55        73.267334
229111         11           1 

In [63]:
labels = pd.read_csv("c:/Python27/qp2_py/labels/labels41_onlyqs.csv")

In [68]:
labels.iloc[0][0]

'English'

In [69]:
from collections import defaultdict
ipuID = defaultdict(lambda:{})
IDtoLabel = defaultdict(str)
count = 0
for item in distances.iterrows():
    speakerID =  item[1]["speakerID"]
    speakerIPU = item[1]["speakerIPU"]
    if speakerIPU not in ipuID[speakerID]:
        ipuID[speakerID][speakerIPU]=count
        IDtoLabel[count] = labels.iloc[speakerID]["Language"]
        count +=1

C:\Python27\lib\site-packages\pandas\core\index.py:641: FutureWarning: scalar indexers for index type Int64Index should be integers and not floating point
  type(self).__name__),FutureWarning)


In [80]:
IDtoLabel[129]

'Mandarin'

In [61]:
count**2

45796

In [84]:
dist_matrix = np.zeros([count,count])

In [85]:
dist_matrix

array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]])

In [88]:
for item in distances.iterrows():
    speakerID = item[1]["speakerID"]
    speakerIPU = item[1]["speakerIPU"]
    compared_speaker = item[1]["comp_speaker"]
    compared_IPU = item[1]["comp_speakerIPU"]
    distance = item[1]["frechetdistance"]
    if compared_IPU in ipuID[compared_speaker]:
        id1 = ipuID[speakerID][speakerIPU]
        id2 = ipuID[compared_speaker][compared_IPU]
        dist_matrix[id1,id2] = distance

In [89]:
dist_matrix

array([[   0.      ,    0.      ,    0.      , ...,  382.150696,
          73.425346,   67.012428],
       [   0.      ,    0.      ,    0.      , ...,  297.149811,
          84.963402,   84.960724],
       [   0.      ,    0.      ,    0.      , ...,  382.100769,
          74.550476,   63.455166],
       ..., 
       [   0.      ,    0.      ,    0.      , ...,    0.      ,
         382.100067,  382.10202 ],
       [   0.      ,    0.      ,    0.      , ...,    0.      ,
           0.      ,    0.      ],
       [   0.      ,    0.      ,    0.      , ...,    0.      ,
           0.      ,    0.      ]])

In [121]:
#np.save("c:/Python27/qp2_py/frechet_distance/half_matrix.txt", dist_matrix, allow_pickle=False)

infile = open("c:/Python27/qp2_py/frechet_distance/half_matrix.txt", "r")
in_matrix = np.load(infile)

In [112]:
#in_matrix

array([ 0.,  0.,  0., ...,  0.,  0.,  0.])

In [93]:
from sklearn.cluster import DBSCAN

cluster = DBSCAN(metric="precomputed")
cluster.fit(dist_matrix)

DBSCAN(algorithm='auto', eps=0.5, leaf_size=30, metric='precomputed',
    min_samples=5, p=None, random_state=None)

In [96]:
cluster.labels_

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  2,  2,  3,  4,  4,  4,  4,  4,  4,  5,  5,  5,  5,  5,  5,  5,
        5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,
        5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,
        5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,
        5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,
        6,  6,  7,  8,  8,  8,  9, 10, 11, 11])

In [130]:
features = [ [feat] for feat in cluster.labels_ ]

In [125]:
clf_labels = [IDtoLabel[i]for i in range(len(features))]

In [131]:
print len(features),len(clf_labels)

214 214


In [133]:
from sklearn.cross_validation import cross_val_score
from sklearn.cross_validation import train_test_split
from sklearn.cross_validation import ShuffleSplit

In [ ]:
param_grid = {'C': [0.001, 0.01, 0.1, 1, 10, 100],
              'gamma': [0.001, 0.01, 0.1, 1, 10, 100]}



#param_grid = {'C': [0.001, 0.01, 0.1, 1, 10, 100]}

from sklearn.grid_search import GridSearchCV
from sklearn.svm import SVC
grid_search = GridSearchCV(SVC(), param_grid, cv=10)

X_train, X_test, y_train, y_test = train_test_split(ipu_features, labels, random_state=0)

grid_search.fit(X_train, y_train)

print(grid_search.best_params_)
print(grid_search.best_score_)

In [135]:
from sklearn.svm import SVC
classifier = SVC()
from sklearn.cross_validation import ShuffleSplit
from sklearn.cross_validation import cross_val_score
shuffle_split = ShuffleSplit(214, n_iter= 10, test_size=.25, train_size=.75)
shuffle_score = cross_val_score(classifier, features, clf_labels, cv=shuffle_split)
print shuffle_score
print shuffle_score.mean()

[ 0.98148148  0.98148148  0.98148148  0.98148148  1.          1.          1.
  1.          1.          0.98148148]
0.990740740741


In [134]:
from sklearn.svm import SVC
classifier = SVC()

X_train, X_test, y_train, y_test = train_test_split(features, clf_labels, random_state=0)
classifier.fit(X_train, y_train)
score = classifier.score(X_test, y_test)
print score

1.0


In [143]:
count_Eng = 0
count_Man = 0
total_Eng = 0
total_Man= 0
count_full = 0
total_instances=0
man_dist = []
eng_dist = []
full_dist = []
for i in range(len(dist_matrix)):
    for j in range(len(dist_matrix)):
        if IDtoLabel[i]==IDtoLabel[j]:
            if IDtoLabel[i]=="English":
                count_Eng+= dist_matrix[i][j]
                eng_dist.append(dist_matrix[i][j])
                total_Eng+=1
            else:
                count_Man+= dist_matrix[i][j]
                man_dist.append(dist_matrix[i][j])
                total_Man+=1
        count_full+= dist_matrix[i][j]
        total_instances+=1
        full_dist.append(dist_matrix[i][j])

        

In [141]:
avg_dist_Eng = count_Eng/float(total_Eng)
avg_dist_Man = count_Man/float(total_Man)
avg_dist = count_full/float(total_instances)

## Calculating distances & significances
- English IPUs are closer to each other than random distances, but Mandarin are even closer to each other
- Mandarin IPUs are closer to other Mandarin IPUs than English IPUs closer to other English IPUs
- By a lot, which is super weird
- And this result is super significant

In [142]:
print avg_dist_Eng
print avg_dist_Man
print avg_dist

44.4459225789
14.339245156
53.6373251001


In [146]:
from scipy.stats import ttest_ind
p_eng = ttest_ind(eng_dist, full_dist)
p_man = ttest_ind(man_dist,full_dist)
print p_eng
print p_man

(-11.202924405297988, 4.2055999483072492e-29)
(-36.230293768111771, 6.0841112134477761e-284)


In [18]:
distance_labels = pd.DataFrame

In [38]:
type(labels.iloc[5])

pandas.core.series.Series

count = 0
for item in distances.iterrows():
    speakerID =  item[1][1]
    if speakersID == count:
        lab = label.iloc[count][0]
        distance_labels.append(lab)
    else: