In [1]:
import os
import pandas as pd
import numpy as np
from Tkinter import *
import tkSnack
root = Tk()
tkSnack.initializeSnack(root)

import matplotlib.pyplot as plt
%matplotlib notebook

C:\Python27\lib\site-packages\IPython\kernel\__init__.py:13: ShimWarning: The `IPython.kernel` package has been deprecated. You should import from ipykernel or jupyter_client instead.
  "You should import from ipykernel or jupyter_client instead.", ShimWarning)


In [2]:
path = "c:/Python27/qp2_py/frechet_distance/current_results/"
allFiles = os.listdir(path)
for name in allFiles:
    fname = path+name
    distances = pd.read_csv(fname, sep="_", header=None)
#print distances

In [3]:
distances.columns= ["speakerID", "speakerIPU", "comp_speaker", "comp_speakerIPU","frechetdistance"]

In [4]:
distances

speakerID  speakerIPU  comp_speaker  comp_speakerIPU  frechetdistance
0               0           0             1                0        65.249969
1               0           0             1                1        66.515404
2               0           0             1                2       274.112701
3               0           0             1                3        84.120514
4               0           0             1                4       157.210114
5               0           0             1                5        79.410965
6               0           0             1                6        66.920204
7               0           0             1                7       129.865005
8               0           0             1                8        87.305168
9               0           0             1                9        70.002014
10              0           0             1               10       121.547394
11              0           0             1               11       133.760040
12              0           0             1               12        70.600319
13              0           0             1               13       116.680733
14              0           0             1               14        88.052719
15              0           0             1               15        31.481182
16              0           0             1               16        87.957268
17              0           0             1               17        89.296844
18              0           0             1               18        56.891933
19              0           0             1               19       353.062225
20              0           0             1               20       109.890099
21              0           0             1               21        68.659462
22              0           0             1               22        83.948578
23              0           0             1               23        88.865791
24              0           0             1               24        37.910965
25              0           0             1               25        77.620163
26              0           0             1               26        67.401115
27              0           0             1               27        25.594454
28              0           0             1               28       120.141197
29              0           0             1               29        75.341499
...           ...         ...           ...              ...              ...
697820         39          36            40                0       116.170029
697821         39          37            40                0       123.451775
697822         39          38            40                0        20.130043
697823         39          39            40                0        66.151596
697824         39          40            40                0        22.590137
697825         39          41            40                0       122.221771
697826         39          42            40                0       118.530029
697827         39          43            40                0        62.730160
697828         39          44            40                0       122.551575
697829         39          45            40                0        20.130892
697830         39          46            40                0        58.145260
697831         39          47            40                0       149.760025
697832         39          48            40                0       143.340012
697833         39          49            40                0       133.429993
697834         39          50            40                0       111.330032
697835         39          51            40                0       168.035416
697836         39          52            40                0       151.880005
697837         39          53            40                0        64.256668
697838         39          54            40                0        73.535805
697839         39          55 

In [5]:
labels = pd.read_csv("c:/Python27/qp2_py/labels/labels41_onlyqs.csv")

In [6]:
labels.iloc[0][0]

'English'

In [7]:
from collections import defaultdict
ipuID = defaultdict(lambda:{})
IDtoLabel = defaultdict(str)
count = 0
for item in distances.iterrows():
    speakerID =  item[1]["speakerID"]
    speakerIPU = item[1]["speakerIPU"]
    if speakerIPU not in ipuID[speakerID]:
        ipuID[speakerID][speakerIPU]=count
        IDtoLabel[count] = labels.iloc[speakerID]["Language"]
        count +=1

C:\Python27\lib\site-packages\pandas\core\index.py:641: FutureWarning: scalar indexers for index type Int64Index should be integers and not floating point
  type(self).__name__),FutureWarning)


In [8]:
IDtoLabel[129]

'Mandarin'

In [9]:
count

1207

In [10]:
count**2

1456849

In [11]:
dist_matrix = np.zeros([count,count])

In [12]:
dist_matrix

array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]])

In [13]:
for item in distances.iterrows():
    speakerID = item[1]["speakerID"]
    speakerIPU = item[1]["speakerIPU"]
    compared_speaker = item[1]["comp_speaker"]
    compared_IPU = item[1]["comp_speakerIPU"]
    distance = item[1]["frechetdistance"]
    if compared_IPU in ipuID[compared_speaker]:
        id1 = ipuID[speakerID][speakerIPU]
        id2 = ipuID[compared_speaker][compared_IPU]
        dist_matrix[id1,id2] = distance

In [14]:
dist_matrix

array([[  0.      ,   0.      ,   0.      , ...,  69.01545 ,  67.204994,
         59.195515],
       [  0.      ,   0.      ,   0.      , ...,  84.960052,  84.960075,
         84.960602],
       [  0.      ,   0.      ,   0.      , ...,  61.030792,  55.655983,
         54.380981],
       ..., 
       [  0.      ,   0.      ,   0.      , ...,   0.      ,   0.      ,
          0.      ],
       [  0.      ,   0.      ,   0.      , ...,   0.      ,   0.      ,
          0.      ],
       [  0.      ,   0.      ,   0.      , ...,   0.      ,   0.      ,
          0.      ]])

In [30]:
print dist_matrix

[[  0.         0.         0.       ...,  69.01545   67.204994  59.195515]
 [  0.         0.         0.       ...,  84.960052  84.960075  84.960602]
 [  0.         0.         0.       ...,  61.030792  55.655983  54.380981]
 ..., 
 [  0.         0.         0.       ...,   0.         0.         0.      ]
 [  0.         0.         0.       ...,   0.         0.         0.      ]
 [  0.         0.         0.       ...,   0.         0.         0.      ]]


In [121]:
#np.save("c:/Python27/qp2_py/frechet_distance/half_matrix.txt", dist_matrix, allow_pickle=False)

infile = open("c:/Python27/qp2_py/frechet_distance/half_matrix.txt", "r")
in_matrix = np.load(infile)

In [112]:
#in_matrix

array([ 0.,  0.,  0., ...,  0.,  0.,  0.])

In [15]:
from sklearn.cluster import DBSCAN

cluster = DBSCAN(metric="precomputed")
cluster.fit(dist_matrix)

DBSCAN(algorithm='auto', eps=0.5, leaf_size=30, metric='precomputed',
    min_samples=5, p=None, random_state=None)

In [16]:
cluster.labels_

array([ 0,  0,  0, ..., 39, 39, 39])

In [17]:
features = [ [feat] for feat in cluster.labels_ ]

In [18]:
clf_labels = [IDtoLabel[i]for i in range(len(features))]

In [19]:
print len(features),len(clf_labels)

1207 1207


In [20]:
from sklearn.cross_validation import cross_val_score
from sklearn.cross_validation import train_test_split
from sklearn.cross_validation import ShuffleSplit

In [ ]:
param_grid = {'C': [0.001, 0.01, 0.1, 1, 10, 100],
              'gamma': [0.001, 0.01, 0.1, 1, 10, 100]}



#param_grid = {'C': [0.001, 0.01, 0.1, 1, 10, 100]}

from sklearn.grid_search import GridSearchCV
from sklearn.svm import SVC
grid_search = GridSearchCV(SVC(), param_grid, cv=10)

X_train, X_test, y_train, y_test = train_test_split(ipu_features, labels, random_state=0)

grid_search.fit(X_train, y_train)

print(grid_search.best_params_)
print(grid_search.best_score_)

In [27]:
from sklearn.svm import SVC
classifier = SVC()
from sklearn.cross_validation import ShuffleSplit
from sklearn.cross_validation import cross_val_score
shuffle_split = ShuffleSplit(1207, n_iter= 10, test_size=.25, train_size=.75)
shuffle_score = cross_val_score(classifier, features, clf_labels, cv=shuffle_split)
print shuffle_score
print shuffle_score.mean()

[ 0.99337748  0.99668874  0.99668874  0.99006623  0.99668874  0.99337748
  0.99006623  0.99668874  0.99668874  0.99006623]
0.994039735099


In [28]:
from sklearn.svm import SVC
classifier = SVC()

X_train, X_test, y_train, y_test = train_test_split(features, clf_labels, random_state=0)
classifier.fit(X_train, y_train)
score = classifier.score(X_test, y_test)
print score

0.993377483444


In [23]:
count_Eng = 0
count_Man = 0
total_Eng = 0
total_Man= 0
count_full = 0
total_instances=0
man_dist = []
eng_dist = []
full_dist = []
for i in range(len(dist_matrix)):
    for j in range(len(dist_matrix)):
        if IDtoLabel[i]==IDtoLabel[j]:
            if IDtoLabel[i]=="English":
                count_Eng+= dist_matrix[i][j]
                eng_dist.append(dist_matrix[i][j])
                total_Eng+=1
            else:
                count_Man+= dist_matrix[i][j]
                man_dist.append(dist_matrix[i][j])
                total_Man+=1
        count_full+= dist_matrix[i][j]
        total_instances+=1
        full_dist.append(dist_matrix[i][j])

        

In [24]:
avg_dist_Eng = count_Eng/float(total_Eng)
avg_dist_Man = count_Man/float(total_Man)
avg_dist = count_full/float(total_instances)

## Calculating distances & significances
### NOTE:  THIS IS NO LONGER ACCURATE AS OF 6/29
- English IPUs are closer to each other than random distances, but Mandarin are even closer to each other
- Mandarin IPUs are closer to other Mandarin IPUs than English IPUs closer to other English IPUs
- By a lot, which is super weird
- And this result is super significant

## (6/29) SUMMARY OF RESULTS (with all but 7 of the IPUs).
### NOTE: STILL MAY NOT BE TOTALLY CORRECT (check distance matrix and frechet distances, results are still suspiciously high)
- English IPUs are closer to each other than to random distances
- English IPUs are closer to each other than Mandarin IPUs
- Mandarin IPUs are also closer to each other than they are to random distances
- All of this is statistically significant

In [25]:
print avg_dist_Eng
print avg_dist_Man
print avg_dist

71.6274103321
72.3356708586
75.3245833469


In [26]:
from scipy.stats import ttest_ind
p_eng = ttest_ind(eng_dist, full_dist)
p_man = ttest_ind(man_dist,full_dist)
print p_eng
print p_man

(-19.192959127799543, 4.3221592908332019e-82)
(-19.010998267846194, 1.4068339227360642e-80)


In [18]:
distance_labels = pd.DataFrame

In [38]:
type(labels.iloc[5])

pandas.core.series.Series

count = 0
for item in distances.iterrows():
    speakerID =  item[1][1]
    if speakersID == count:
        lab = label.iloc[count][0]
        distance_labels.append(lab)
    else: